# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/victor/Dropbox/Dropbox/Doutorado/Disciplinas/Metaheuristica/BinPacking-Meta

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/victor/Dropbox/Dropbox/Doutorado/Disciplinas/Metaheuristica/BinPacking-Meta

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/Dropbox/Dropbox/Doutorado/Disciplinas/Metaheuristica/BinPacking-Meta/CMakeFiles /home/victor/Dropbox/Dropbox/Doutorado/Disciplinas/Metaheuristica/BinPacking-Meta/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/victor/Dropbox/Dropbox/Doutorado/Disciplinas/Metaheuristica/BinPacking-Meta/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named binpack

# Build rule for target.
binpack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binpack
.PHONY : binpack

# fast build rule for target.
binpack/fast:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/build
.PHONY : binpack/fast

BuscaLocal.o: BuscaLocal.cpp.o

.PHONY : BuscaLocal.o

# target to build an object file
BuscaLocal.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/BuscaLocal.cpp.o
.PHONY : BuscaLocal.cpp.o

BuscaLocal.i: BuscaLocal.cpp.i

.PHONY : BuscaLocal.i

# target to preprocess a source file
BuscaLocal.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/BuscaLocal.cpp.i
.PHONY : BuscaLocal.cpp.i

BuscaLocal.s: BuscaLocal.cpp.s

.PHONY : BuscaLocal.s

# target to generate assembly for a file
BuscaLocal.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/BuscaLocal.cpp.s
.PHONY : BuscaLocal.cpp.s

Container.o: Container.cpp.o

.PHONY : Container.o

# target to build an object file
Container.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Container.cpp.o
.PHONY : Container.cpp.o

Container.i: Container.cpp.i

.PHONY : Container.i

# target to preprocess a source file
Container.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Container.cpp.i
.PHONY : Container.cpp.i

Container.s: Container.cpp.s

.PHONY : Container.s

# target to generate assembly for a file
Container.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Container.cpp.s
.PHONY : Container.cpp.s

Decoder.o: Decoder.cpp.o

.PHONY : Decoder.o

# target to build an object file
Decoder.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Decoder.cpp.o
.PHONY : Decoder.cpp.o

Decoder.i: Decoder.cpp.i

.PHONY : Decoder.i

# target to preprocess a source file
Decoder.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Decoder.cpp.i
.PHONY : Decoder.cpp.i

Decoder.s: Decoder.cpp.s

.PHONY : Decoder.s

# target to generate assembly for a file
Decoder.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Decoder.cpp.s
.PHONY : Decoder.cpp.s

GRASP.o: GRASP.cpp.o

.PHONY : GRASP.o

# target to build an object file
GRASP.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/GRASP.cpp.o
.PHONY : GRASP.cpp.o

GRASP.i: GRASP.cpp.i

.PHONY : GRASP.i

# target to preprocess a source file
GRASP.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/GRASP.cpp.i
.PHONY : GRASP.cpp.i

GRASP.s: GRASP.cpp.s

.PHONY : GRASP.s

# target to generate assembly for a file
GRASP.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/GRASP.cpp.s
.PHONY : GRASP.cpp.s

Instance.o: Instance.cpp.o

.PHONY : Instance.o

# target to build an object file
Instance.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Instance.cpp.o
.PHONY : Instance.cpp.o

Instance.i: Instance.cpp.i

.PHONY : Instance.i

# target to preprocess a source file
Instance.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Instance.cpp.i
.PHONY : Instance.cpp.i

Instance.s: Instance.cpp.s

.PHONY : Instance.s

# target to generate assembly for a file
Instance.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Instance.cpp.s
.PHONY : Instance.cpp.s

SA.o: SA.cpp.o

.PHONY : SA.o

# target to build an object file
SA.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/SA.cpp.o
.PHONY : SA.cpp.o

SA.i: SA.cpp.i

.PHONY : SA.i

# target to preprocess a source file
SA.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/SA.cpp.i
.PHONY : SA.cpp.i

SA.s: SA.cpp.s

.PHONY : SA.s

# target to generate assembly for a file
SA.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/SA.cpp.s
.PHONY : SA.cpp.s

Solution.o: Solution.cpp.o

.PHONY : Solution.o

# target to build an object file
Solution.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solution.cpp.o
.PHONY : Solution.cpp.o

Solution.i: Solution.cpp.i

.PHONY : Solution.i

# target to preprocess a source file
Solution.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solution.cpp.i
.PHONY : Solution.cpp.i

Solution.s: Solution.cpp.s

.PHONY : Solution.s

# target to generate assembly for a file
Solution.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solution.cpp.s
.PHONY : Solution.cpp.s

Solver.o: Solver.cpp.o

.PHONY : Solver.o

# target to build an object file
Solver.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solver.cpp.o
.PHONY : Solver.cpp.o

Solver.i: Solver.cpp.i

.PHONY : Solver.i

# target to preprocess a source file
Solver.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solver.cpp.i
.PHONY : Solver.cpp.i

Solver.s: Solver.cpp.s

.PHONY : Solver.s

# target to generate assembly for a file
Solver.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/Solver.cpp.s
.PHONY : Solver.cpp.s

brkgaAPI/Population.o: brkgaAPI/Population.cpp.o

.PHONY : brkgaAPI/Population.o

# target to build an object file
brkgaAPI/Population.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/brkgaAPI/Population.cpp.o
.PHONY : brkgaAPI/Population.cpp.o

brkgaAPI/Population.i: brkgaAPI/Population.cpp.i

.PHONY : brkgaAPI/Population.i

# target to preprocess a source file
brkgaAPI/Population.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/brkgaAPI/Population.cpp.i
.PHONY : brkgaAPI/Population.cpp.i

brkgaAPI/Population.s: brkgaAPI/Population.cpp.s

.PHONY : brkgaAPI/Population.s

# target to generate assembly for a file
brkgaAPI/Population.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/brkgaAPI/Population.cpp.s
.PHONY : brkgaAPI/Population.cpp.s

lp.o: lp.cpp.o

.PHONY : lp.o

# target to build an object file
lp.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/lp.cpp.o
.PHONY : lp.cpp.o

lp.i: lp.cpp.i

.PHONY : lp.i

# target to preprocess a source file
lp.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/lp.cpp.i
.PHONY : lp.cpp.i

lp.s: lp.cpp.s

.PHONY : lp.s

# target to generate assembly for a file
lp.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/lp.cpp.s
.PHONY : lp.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/binpack.dir/build.make CMakeFiles/binpack.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... binpack"
	@echo "... BuscaLocal.o"
	@echo "... BuscaLocal.i"
	@echo "... BuscaLocal.s"
	@echo "... Container.o"
	@echo "... Container.i"
	@echo "... Container.s"
	@echo "... Decoder.o"
	@echo "... Decoder.i"
	@echo "... Decoder.s"
	@echo "... GRASP.o"
	@echo "... GRASP.i"
	@echo "... GRASP.s"
	@echo "... Instance.o"
	@echo "... Instance.i"
	@echo "... Instance.s"
	@echo "... SA.o"
	@echo "... SA.i"
	@echo "... SA.s"
	@echo "... Solution.o"
	@echo "... Solution.i"
	@echo "... Solution.s"
	@echo "... Solver.o"
	@echo "... Solver.i"
	@echo "... Solver.s"
	@echo "... brkgaAPI/Population.o"
	@echo "... brkgaAPI/Population.i"
	@echo "... brkgaAPI/Population.s"
	@echo "... lp.o"
	@echo "... lp.i"
	@echo "... lp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

